import React, { useState } from 'react';
import { Send } from 'lucide-react';
import './App.css';

function App() {
  const [messages, setMessages] = useState([
    { id: 1, text: 'Hello! I am your Smart AI Assistant. How can I help you today?', sender: 'ai' }
  ]);
  const [input, setInput] = useState('');

  const getAIResponse = (userMessage) => {
    const message = userMessage.toLowerCase().trim();

    if (message.includes('hello') || message.includes('hi') || message.includes('hey')) {
      return 'Hello! Nice to meet you. How can I assist you today?';
    } else if (message.includes('who are you') || message.includes('what are you')) {
      return 'I am a Smart AI Assistant, a prototype designed to help answer questions and provide assistance. I can respond to basic queries and engage in conversation.';
    } else if (message.includes('how are you') || message.includes('how do you do')) {
      return 'I\'m doing well, thank you for asking! As an AI, I\'m always ready to help. How are you doing?';
    } else if (message.includes('thank you') || message.includes('thanks')) {
      return 'You\'re welcome! Is there anything else I can help you with?';
    } else if (message.includes('bye') || message.includes('goodbye')) {
      return 'Goodbye! It was nice chatting with you. Feel free to come back anytime!';
    } else if (message.includes('what can you do') || message.includes('help')) {
      return 'I can answer basic questions, engage in conversation, and provide assistance. Try asking me about myself or just say hello!';
    } else {
      return `You said: "${userMessage}". This is a prototype response. In a real app, this would be generated by AI.`;
    }
  };

  const handleSend = () => {
    if (input.trim()) {
      const newMessage = { id: messages.length + 1, text: input, sender: 'user' };
      setMessages([...messages, newMessage]);
      const userInput = input;
      setInput('');

      // Mock AI response
      setTimeout(() => {
        const aiResponse = {
          id: messages.length + 2,
          text: getAIResponse(userInput),
          sender: 'ai'
        };
        setMessages(prev => [...prev, aiResponse]);
      }, 1000);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      handleSend();
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>Smart AI Base Prototype</h1>
      </header>
      <div className="chat-container">
        <div className="messages">
          {messages.map(msg => (
            <div key={msg.id} className={`message ${msg.sender}`}>
              <div className="message-content">{msg.text}</div>
            </div>
          ))}
        </div>
        <div className="input-container">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Type your message..."
            className="message-input"
          />
          <button onClick={handleSend} className="send-button">
            <Send size={20} />
          </button>
        </div>
      </div>
    </div>
  );
}

export default App;
